/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';

export function Desk(props) {
  const { nodes, materials } = useGLTF('./Desk.gltf');

  // TODO: merge + bake the scene

  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={108702.83 / 50000} color='#31abff' position={[-0.17, 2.91, -3.4]} rotation={[Math.PI / 2, 0, -1.13]} castShadow />
      <spotLight intensity={81527.12 / 50000} color='#FFC47C' position={[-6.25, 3.26, -0.28]} rotation={[Math.PI / 2, 0, -1.99]} castShadow />
      <mesh
        name='Desk'
        castShadow
        receiveShadow
        geometry={nodes.Desk.geometry}
        material={materials.Background}
        position={[0.03, 0, -1.78]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        name='Mouse'
        castShadow
        receiveShadow
        geometry={nodes.Mouse.geometry}
        material={materials['White Gloss (Mug, Lamp, Mouse)']}
        position={[-4.11, 0, 3.54]}
        rotation={[-Math.PI, 0.57, -Math.PI]}
      />
      <group name='Coffee_Cup' position={[-3.98, 0, 1.31]} rotation={[Math.PI, -0.57, Math.PI]}>
        <mesh
          name='Coffee_Cup'
          castShadow
          receiveShadow
          geometry={nodes.Coffee_Cup_1.geometry}
          material={materials['White Gloss (Mug, Lamp, Mouse)']}
        />
        <mesh name='Coffee' castShadow receiveShadow geometry={nodes.Coffee_Cup_2.geometry} material={materials['Black (Cofee)']} />
      </group>
      <group name='Lamp' position={[-7.03, 3.59, -0.15]} rotation={[-1.58, 0.48, -1.56]}>
        <mesh name='Lamp_1' castShadow receiveShadow geometry={nodes.Lamp_1.geometry} material={materials['White Gloss (Mug, Lamp, Mouse)']} />
        <mesh name='Lamp_2' castShadow receiveShadow geometry={nodes.Lamp_2.geometry} material={materials['Wood (Lamp)']} />
      </group>
      <group name='Keyboard' position={[0.43, 0.04, 3.73]} rotation={[-3.1, 0, -3.14]}>
        <mesh name='Keyboard_1' castShadow receiveShadow geometry={nodes.Keyboard_1.geometry} material={materials['Metal (Monitor, Keyboard Top)']} />
        <mesh name='Keyboard_2' castShadow receiveShadow geometry={nodes.Keyboard_2.geometry} material={materials['Metal (Keyboard)']} />
        <mesh name='Keyboard_3' castShadow receiveShadow geometry={nodes.Keyboard_3.geometry} material={materials['Black (Keys, Pot)']} />
      </group>
      <group name='Plant' position={[3.48, 0, -2.65]} rotation={[Math.PI, -0.04, Math.PI]}>
        <mesh name='Plant_1' castShadow receiveShadow geometry={nodes.Plant_1.geometry} material={materials['Black (Keys, Pot)']} />
        <mesh name='Plant_2' castShadow receiveShadow geometry={nodes.Plant_2.geometry} material={materials.Plant} />
        <mesh name='Plant_3' castShadow receiveShadow geometry={nodes.Plant_3.geometry} material={materials['Plant Dirt']} />
      </group>
      <group name='MacBook' position={[5.56, 0.11, 0.47]} rotation={[-1.56, -0.01, 2.62]}>
        <mesh name='Macbook' castShadow receiveShadow geometry={nodes.Macbook.geometry} material={materials['Metal (Monitor, Keyboard Top)']} />
        <mesh name='Macbook_1' castShadow receiveShadow geometry={nodes.Macbook_1.geometry} material={materials['Bezel Material']} />
        <mesh name='Macbook_2' castShadow receiveShadow geometry={nodes.Macbook_2.geometry} material={materials['Apple Logo']} />
        <mesh name='Macbook_3' castShadow receiveShadow geometry={nodes.Macbook_3.geometry} material={materials['Black (Cofee)']} />
        <mesh name='Macbook_4' castShadow receiveShadow geometry={nodes.Macbook_4.geometry} material={materials['Black (Keys, Pot)']} />
        <mesh name='Macbook_5' castShadow receiveShadow geometry={nodes.Macbook_5.geometry} material={materials['Keys Light']} />
        <mesh
          name='MacBook_Screen'
          castShadow
          receiveShadow
          geometry={nodes.MacBook_Screen.geometry}
          material={materials.DisplayGlass}
          rotation={[0, 0, -Math.PI]}
        />
      </group>
      <group name='Monitor' position={[-0.22, 4.12, -0.42]} rotation={[Math.PI, -1.52, Math.PI]}>
        <mesh name='Monitor_1' castShadow receiveShadow geometry={nodes.Monitor_1.geometry} material={materials['Metal (Monitor, Keyboard Top)']} />
        <mesh name='Monitor_2' castShadow receiveShadow geometry={nodes.Monitor_2.geometry} material={materials.DisplayGlass} />
        <mesh
          name='Monitor_Screen'
          castShadow
          receiveShadow
          geometry={nodes.Monitor_Screen.geometry}
          material={materials['Pink Screen Of Death']}
          position={[-0.01, 0, 0]}
          rotation={[0, 0, -Math.PI]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/Desk.gltf');
